"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _auth_sign_in from './auth-sign-in.bones.json'
import _auth_sign_up from './auth-sign-up.bones.json'
import _today_shell from './today-shell.bones.json'
import _history_shell from './history-shell.bones.json'
import _program_shell from './program-shell.bones.json'
import _recommendation_shell from './recommendation-shell.bones.json'

registerBones({
  "auth-sign-in": _auth_sign_in,
  "auth-sign-up": _auth_sign_up,
  "today-shell": _today_shell,
  "history-shell": _history_shell,
  "program-shell": _program_shell,
  "recommendation-shell": _recommendation_shell,
})
