"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _auth_sign_in from './auth-sign-in.bones.json'
import _auth_sign_up from './auth-sign-up.bones.json'

registerBones({
  "auth-sign-in": _auth_sign_in,
  "auth-sign-up": _auth_sign_up,
})
