name = "workout-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true

[[kv_namespaces]]
binding = "KV"
id = "3e40683700fc4e36a4a27c91b5242476"
preview_id = "75cff9c2147c480eb96df49b02e46052"

[vars]
