/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user product state
         * @description Returns the authenticated user identity together with onboarding, profile, and active-program state.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user state. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get onboarding state
         * @description Returns saved onboarding draft, completion state, and current normalized profile summary.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current onboarding state. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnboardingStateResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Save onboarding draft
         * @description Persists draft onboarding answers without completing onboarding or generating a program.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OnboardingDraft"];
                };
            };
            responses: {
                /** @description Draft saved. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnboardingDraftSaveResponse"];
                    };
                };
                /** @description Invalid onboarding draft body. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete onboarding and create recommendation draft
         * @description Validates onboarding answers, stores the normalized profile, marks onboarding complete, and creates the current recommendation draft without activating a program yet.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OnboardingAnswers"];
                };
            };
            responses: {
                /** @description Onboarding completed and recommendation draft created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnboardingCompleteResponse"];
                    };
                };
                /** @description Invalid onboarding answers. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Catalog or user state cannot satisfy onboarding completion. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get today's workout
         * @description Returns the generated workout plan for the provided date or for today when no date query parameter is supplied.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Optional workout date in YYYY-MM-DD format. */
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Workout plan or rest-day response. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkoutTodayResponse"];
                    };
                };
                /** @description Invalid date. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Onboarding not completed or no active program exists. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/program": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get active program
         * @description Returns the active program definition together with current progression metadata and user set counts.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active program. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProgramResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Onboarding not completed or no active program exists. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Save active program
         * @description Creates a new active program version and reseeds progression state from the previous version.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProgramDefinition"];
                };
            };
            responses: {
                /** @description Program saved. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProgramMutationResponse"];
                    };
                };
                /** @description Invalid program body. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/program/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset active program
         * @description Resets the active program to the built-in default program. Requires the X-Reset-Token header.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Shared reset token required to reset the active program. */
                    "X-Reset-Token": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Program reset. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProgramMutationResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Invalid reset token. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/program/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate active program from onboarding profile
         * @description Uses the stored normalized profile and global exercise catalog to generate a fresh active program version without relying on frontend program composition.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Program regenerated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GeneratedProgramResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Onboarding not completed or no normalized profile exists. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendation-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current recommendation draft */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current recommendation draft. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecommendationDraftResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Recommendation draft not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create or refresh recommendation draft from stored profile
         * @description Builds an editable recommendation draft from the stored normalized profile without activating a program.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recommendation draft created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecommendationDraftResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Stored onboarding/profile or catalog state cannot satisfy draft creation. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendation-draft/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Choose recommendation draft structure */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecommendationDraftStructureSelectRequest"];
                };
            };
            responses: {
                /** @description Recommendation draft structure updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecommendationDraftResponse"];
                    };
                };
                /** @description Invalid structure selection request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Recommendation draft not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Draft is stale, activated, or structure is invalid for the current draft. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/recommendation-draft/exercise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Replace recommendation draft exercise in a slot */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecommendationDraftExerciseReplaceRequest"];
                };
            };
            responses: {
                /** @description Recommendation draft exercise updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecommendationDraftResponse"];
                    };
                };
                /** @description Invalid exercise replacement request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Recommendation draft not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Draft is stale, activated, slot is missing, or exercise is not valid for the slot. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/recommendation-draft/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate current recommendation draft */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecommendationDraftActivateRequest"];
                };
            };
            responses: {
                /** @description Recommendation draft activated into a normal active program version. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecommendationDraftActivateResponse"];
                    };
                };
                /** @description Invalid activation request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Recommendation draft not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Draft is stale or activation state is invalid. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Activation failed after partial orchestration. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progression/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run progression evaluation
         * @description Evaluates recent session performance and updates progression state for the active program.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Progression run completed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProgressionRunResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Onboarding not completed or no active program exists. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create workout log
         * @description Creates a workout session from structured JSON. X-Workout-Date can override the session date.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional workout date override in YYYY-MM-DD format. */
                    "X-Workout-Date"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["JsonLogRequest"];
                };
            };
            responses: {
                /** @description Workout session created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogCreateResponse"];
                    };
                };
                /** @description Invalid request body or date header. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Onboarding not completed, no active program exists, or a log already exists for the date. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List workout sessions
         * @description Returns stored workout sessions, optionally filtered by date and limited to the requested count.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Optional max sessions to return. Invalid values fall back to 20. */
                    limit?: string;
                    /** @description Optional session date filter in YYYY-MM-DD format. */
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionsListResponse"];
                    };
                };
                /** @description Invalid date filter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get workout session
         * @description Returns a full workout session record including matched exercises and set values.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Workout session identifier. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session record. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkoutSessionRecord"];
                    };
                };
                /** @description Missing or invalid Clerk Bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Session not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Clerk JWKS unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MeResponse: {
            user: {
                /** @example user_123 */
                id: string;
                /** @example demo@example.com */
                username: string | null;
                /**
                 * @description UTC timestamp in ISO 8601 format.
                 * @example 2026-03-29T12:00:00.000Z
                 */
                created_at: string;
            };
            lifecycle: {
                /** @enum {boolean} */
                user_exists: true;
                onboarding_completed: boolean;
                has_active_program: boolean;
            };
            onboarding: {
                /** @enum {string} */
                status: "not_started" | "draft" | "completed";
                completed: boolean;
                questionnaireVersion: string | null;
                answersUpdatedAt: string | null;
                completedAt: string | null;
                answers: components["schemas"]["OnboardingDraft"];
            };
            profile: {
                /** @example profile-v1 */
                version: string;
                /** @example strength */
                primary_goal: string;
                /** @example beginner */
                experience_level: string;
                /** @example 3 */
                training_days_per_week: number;
                /** @example 45 */
                session_duration_minutes: number;
                /**
                 * @description UTC timestamp in ISO 8601 format.
                 * @example 2026-03-29T12:00:00.000Z
                 */
                updated_at: string;
            } | null;
            active_program: {
                /** @example program_123 */
                version_id: string;
                /** @example generated_three_day_strength */
                key: string;
                /** @example Strength Plan */
                name: string;
                /** @example generated */
                source: string;
                /**
                 * @description UTC timestamp in ISO 8601 format.
                 * @example 2026-03-29T12:00:00.000Z
                 */
                updated_at: string;
            } | null;
        };
        OnboardingDraft: {
            /** @example onboarding-v1 */
            questionnaireVersion?: string;
            /**
             * @example [
             *       "strength",
             *       "general_fitness"
             *     ]
             */
            goals?: components["schemas"]["OnboardingGoal"][];
            experienceLevel?: components["schemas"]["ExperienceLevel"];
            /** @example 3 */
            trainingDaysPerWeek?: number;
            /** @example 45 */
            sessionDurationMinutes?: number;
            /**
             * @example [
             *       "bodyweight",
             *       "bands"
             *     ]
             */
            equipmentAccess?: components["schemas"]["EquipmentAccess"][];
            /**
             * @example [
             *       "upper_body",
             *       "core"
             *     ]
             */
            focusAreas?: components["schemas"]["FocusArea"][];
            /**
             * @example [
             *       "wrist_sensitive"
             *     ]
             */
            limitations?: components["schemas"]["LimitationTag"][];
            /**
             * @example [
             *       "balanced",
             *       "low_impact"
             *     ]
             */
            preferredStyles?: components["schemas"]["PreferredStyle"][];
        } | null;
        /** @enum {string} */
        OnboardingGoal: "strength" | "muscle" | "general_fitness" | "mobility";
        /** @enum {string} */
        ExperienceLevel: "beginner" | "intermediate" | "advanced";
        /** @enum {string} */
        EquipmentAccess: "bodyweight" | "dumbbells" | "bands" | "bench" | "pullup_bar";
        /** @enum {string} */
        FocusArea: "upper_body" | "lower_body" | "core" | "mobility";
        /** @enum {string} */
        LimitationTag: "wrist_sensitive" | "knee_sensitive" | "lower_back_sensitive" | "shoulder_sensitive";
        /** @enum {string} */
        PreferredStyle: "balanced" | "strength_bias" | "mobility_bias" | "low_impact";
        ErrorResponse: {
            /** @example Invalid request */
            error: string;
            /** @example Invalid date. Use format: 2026-03-11 */
            detail?: string;
        };
        OnboardingStateResponse: {
            /** @enum {string} */
            status: "not_started" | "draft" | "completed";
            completed: boolean;
            /** @example onboarding-v1 */
            questionnaireVersion: string | null;
            /** @example 2026-04-01T12:00:00.000Z */
            answersUpdatedAt: string | null;
            /** @example 2026-04-01T12:05:00.000Z */
            completedAt: string | null;
            answers: components["schemas"]["OnboardingDraft"];
            profile: components["schemas"]["OnboardingProfileSummary"];
        };
        OnboardingProfileSummary: {
            /** @example profile-v1 */
            version: string;
            /** @example strength */
            primary_goal: string;
            /** @example 3 */
            training_days_per_week: number;
            /** @example 45 */
            session_duration_minutes: number;
            /**
             * @description UTC timestamp in ISO 8601 format.
             * @example 2026-03-29T12:00:00.000Z
             */
            updated_at: string;
        } | null;
        OnboardingDraftSaveResponse: {
            /** @enum {boolean} */
            ok: true;
            /** @example Onboarding draft saved */
            message: string;
            /** @example onboarding-v1 */
            questionnaire_version: string;
            /**
             * @description UTC timestamp in ISO 8601 format.
             * @example 2026-03-29T12:00:00.000Z
             */
            updated_at: string;
            /** @example null */
            completed_at: string | null;
        };
        OnboardingCompleteResponse: {
            /** @enum {boolean} */
            ok: true;
            /** @example Onboarding completed */
            message: string;
            onboarding: {
                /** @enum {boolean} */
                completed: true;
                /**
                 * @description UTC timestamp in ISO 8601 format.
                 * @example 2026-03-29T12:00:00.000Z
                 */
                completed_at: string;
                /** @example onboarding-v1 */
                questionnaire_version: string;
            };
            profile: {
                /** @example profile-v1 */
                version: string;
                /** @example strength */
                primary_goal: string;
                /** @example 3 */
                training_days_per_week: number;
                /** @example 45 */
                session_duration_minutes: number;
            };
            recommendation_draft: components["schemas"]["RecommendationDraftResponse"];
        };
        RecommendationDraftResponse: {
            /** @example rd_123 */
            id: string;
            status: components["schemas"]["RecommendationDraftStatus"];
            /** @example onboarding_123 */
            source_onboarding_answer_id: string | null;
            /** @example profile_123 */
            source_profile_id: string | null;
            /** @example generator-v1 */
            generator_version: string;
            /** @example catalog-v1 */
            catalog_seed_version: string;
            /** @example 3_day */
            selected_structure_id: string;
            /** @example null */
            activated_program_id: string | null;
            /**
             * @description UTC timestamp in ISO 8601 format.
             * @example 2026-03-29T12:00:00.000Z
             */
            created_at: string;
            /**
             * @description UTC timestamp in ISO 8601 format.
             * @example 2026-03-29T12:00:00.000Z
             */
            updated_at: string;
            /**
             * @description UTC timestamp in ISO 8601 format.
             * @example null
             */
            activated_at: string | null;
            draft: components["schemas"]["RecommendationDraftJson"];
        };
        /** @enum {string} */
        RecommendationDraftStatus: "draft" | "activated";
        RecommendationDraftJson: {
            status: components["schemas"]["RecommendationDraftStatus"];
            profile_snapshot: components["schemas"]["RecommendationDraftProfileSnapshot"];
            structures: components["schemas"]["RecommendationDraftStructure"][];
            /** @example 3_day */
            selected_structure_id: string;
            exercise_slots: components["schemas"]["RecommendationDraftExerciseSlot"][];
            /** @example generator-v1 */
            generator_version: string;
            /** @example catalog-v1 */
            catalog_seed_version: string;
            activation_context?: components["schemas"]["RecommendationDraftActivationContext"];
        };
        RecommendationDraftProfileSnapshot: {
            /** @example strength */
            primaryGoal: string;
            /** @example beginner */
            experienceLevel: string;
            /** @example 3 */
            trainingDaysPerWeek: number;
            /** @example 45 */
            sessionDurationMinutes: number;
            /** @example three_day */
            splitPreference: string;
            /** @example standard */
            volumeLevel: string;
            /**
             * @example [
             *       "bodyweight",
             *       "bands"
             *     ]
             */
            equipmentAccess: string[];
            /**
             * @example [
             *       "upper_body",
             *       "core"
             *     ]
             */
            focusAreas: string[];
            /** @example [] */
            limitationTags: string[];
            /**
             * @example [
             *       "balanced"
             *     ]
             */
            preferredStyles: string[];
            /**
             * @example [
             *       "strength",
             *       "upper",
             *       "core"
             *     ]
             */
            preferredWorkoutTags: string[];
            /** @example [] */
            excludedWorkoutTags: string[];
        };
        RecommendationDraftStructure: {
            /** @example 3_day */
            id: string;
            /** @example 3-day split */
            label: string;
            /** @example Mon / Wed / Fri */
            description: string;
            /**
             * @example {
             *       "monday": "A",
             *       "tuesday": "rest",
             *       "wednesday": "B",
             *       "thursday": "rest",
             *       "friday": "C",
             *       "saturday": "rest",
             *       "sunday": "rest"
             *     }
             */
            schedule: {
                monday?: string;
                tuesday?: string;
                wednesday?: string;
                thursday?: string;
                friday?: string;
                saturday?: string;
                sunday?: string;
            };
            workouts: components["schemas"]["RecommendationDraftStructureWorkout"][];
            /** @example true */
            recommended: boolean;
        };
        RecommendationDraftStructureWorkout: {
            /** @example A */
            key: string;
            /** @example Workout A */
            name: string;
            /**
             * @example [
             *       "strength",
             *       "upper",
             *       "core"
             *     ]
             */
            tags: string[];
        };
        RecommendationDraftExerciseSlot: {
            /** @example A:0 */
            slot_id: string;
            /** @example A */
            workout_key: string;
            /** @example Workout A */
            workout_name: string;
            /** @example 0 */
            slot_index: number;
            /**
             * @example [
             *       "strength",
             *       "upper",
             *       "core"
             *     ]
             */
            blueprint_tags: string[];
            /** @example push_up */
            recommended_exercise_id: string;
            /** @example push_up */
            selected_exercise_id: string;
            options: components["schemas"]["RecommendationDraftExerciseOption"][];
        };
        RecommendationDraftExerciseOption: {
            /** @example catalog_pushups */
            catalog_exercise_id: string;
            /** @example push_up */
            exercise_id: string;
            /** @example Push Up */
            name: string;
            type: components["schemas"]["RecommendationDraftExerciseType"];
            /** @example 8 */
            target_min: number;
            /** @example 12 */
            target_max: number;
            /** @example 4 */
            max_sets: number;
            /** @example true */
            recommended: boolean;
        };
        /** @enum {string} */
        RecommendationDraftExerciseType: "reps" | "time" | "cycles";
        RecommendationDraftActivationContext: {
            /** @example program_123 */
            activated_program_id: string | null;
            /**
             * @description UTC timestamp in ISO 8601 format.
             * @example 2026-04-17T12:00:00.000Z
             */
            activated_at: string | null;
        };
        OnboardingAnswers: {
            /** @example onboarding-v1 */
            questionnaireVersion?: string;
            /**
             * @example [
             *       "strength",
             *       "general_fitness"
             *     ]
             */
            goals: components["schemas"]["OnboardingGoal"][];
            experienceLevel: components["schemas"]["ExperienceLevel"];
            /** @example 3 */
            trainingDaysPerWeek: number;
            /** @example 45 */
            sessionDurationMinutes: number;
            /**
             * @example [
             *       "bodyweight",
             *       "bands"
             *     ]
             */
            equipmentAccess: components["schemas"]["EquipmentAccess"][];
            /**
             * @example [
             *       "upper_body",
             *       "core"
             *     ]
             */
            focusAreas: components["schemas"]["FocusArea"][];
            /**
             * @example [
             *       "wrist_sensitive"
             *     ]
             */
            limitations?: components["schemas"]["LimitationTag"][];
            /**
             * @example [
             *       "balanced",
             *       "low_impact"
             *     ]
             */
            preferredStyles: components["schemas"]["PreferredStyle"][];
        };
        WorkoutTodayResponse: components["schemas"]["RestDayResponse"] | components["schemas"]["WorkoutPlanResponse"];
        RestDayResponse: {
            /** @enum {string} */
            type: "rest";
            /**
             * @description Date string in YYYY-MM-DD format.
             * @example 2026-03-11
             */
            date: string;
            /** @example Today is a rest day */
            message: string;
        };
        WorkoutPlanResponse: {
            /**
             * @description Date string in YYYY-MM-DD format.
             * @example 2026-03-11
             */
            date: string;
            /** @example A */
            type: string;
            /** @example Workout A */
            name: string;
            exercises: (components["schemas"]["WorkoutExerciseReps"] | components["schemas"]["WorkoutExerciseTime"] | components["schemas"]["WorkoutExerciseCycles"])[];
            /** @example default */
            program_id: string;
            /** @example program_123 */
            program_version_id: string;
        };
        WorkoutExerciseReps: {
            /** @example pushups */
            id: string;
            /** @example Push-ups */
            name: string;
            /** @example 2 */
            sets: number;
            /** @example 3 */
            max_sets: number;
            /** @enum {string} */
            type: "reps";
            reps: components["schemas"]["TargetRange"];
        };
        TargetRange: {
            /** @example 8 */
            min: number;
            /** @example 12 */
            max: number;
        };
        WorkoutExerciseTime: {
            /** @example pushups */
            id: string;
            /** @example Push-ups */
            name: string;
            /** @example 2 */
            sets: number;
            /** @example 3 */
            max_sets: number;
            /** @enum {string} */
            type: "time";
            duration: components["schemas"]["TargetRange"];
        };
        WorkoutExerciseCycles: {
            /** @example pushups */
            id: string;
            /** @example Push-ups */
            name: string;
            /** @example 2 */
            sets: number;
            /** @example 3 */
            max_sets: number;
            /** @enum {string} */
            type: "cycles";
            cycles: components["schemas"]["TargetRange"];
        };
        ProgramResponse: components["schemas"]["ProgramDefinition"] & {
            /** @example program_123 */
            version_id: string;
            /** @example api */
            source: string;
            /**
             * @example {
             *       "pushups": 2,
             *       "squats": 3
             *     }
             */
            userSets: {
                [key: string]: number;
            };
            progressionState: {
                [key: string]: components["schemas"]["ProgressionStateValue"];
            };
            generator_metadata: components["schemas"]["GeneratedProgramMetadata"];
            generated_program_metadata: components["schemas"]["StoredGeneratedProgramMetadata"];
            progression_events: components["schemas"]["ProgramProgressionEvent"][];
            program_runtime_state: components["schemas"]["ProgramRuntimeState"];
            active_version: components["schemas"]["ActiveProgramVersion"];
            current_version_changes: components["schemas"]["CurrentVersionChanges"];
        };
        ProgramSchedule: {
            /** @example A */
            monday: string;
            /** @example B */
            tuesday: string;
            /** @example stretch */
            wednesday: string;
            /** @example A */
            thursday: string;
            /** @example B */
            friday: string;
            /** @example stretch */
            saturday: string;
            /** @example rest */
            sunday: string;
        };
        ProgramWorkout: {
            /** @example Workout A */
            name: string;
            exercises: (components["schemas"]["ProgramExerciseReps"] | components["schemas"]["ProgramExerciseTime"] | components["schemas"]["ProgramExerciseCycles"])[];
        };
        ProgramExerciseReps: {
            /** @example pushups */
            id: string;
            /** @example Push-ups */
            name: string;
            /** @enum {string} */
            type: "reps";
            /** @example 3 */
            max_sets: number;
            reps: components["schemas"]["TargetRange"];
        };
        ProgramExerciseTime: {
            /** @example side_plank */
            id: string;
            /** @example Side Plank */
            name: string;
            /** @enum {string} */
            type: "time";
            /** @example 3 */
            max_sets: number;
            duration: components["schemas"]["TargetRange"];
        };
        ProgramExerciseCycles: {
            /** @example breathing */
            id: string;
            /** @example Breathing */
            name: string;
            /** @enum {string} */
            type: "cycles";
            /** @example 1 */
            max_sets: number;
            cycles: components["schemas"]["TargetRange"];
        };
        ProgressionStateValue: {
            /** @example 2 */
            sets: number;
            /** @example 8 */
            min: number;
            /** @example 12 */
            max: number;
            /** @example 2026-03-27 */
            last_progression: string | null;
        };
        GeneratedProgramMetadata: {
            /** @example generator-v1 */
            version: string;
            /** @example catalog-v1 */
            catalog_seed_version: string;
        } | null;
        StoredGeneratedProgramMetadata: {
            /** @example regenerate */
            generation_reason: string;
            /** @example profile-v1 */
            profile_version: string | null;
            /**
             * @description UTC timestamp in ISO 8601 format.
             * @example 2026-03-29T12:00:00.000Z
             */
            created_at: string;
            input_summary: components["schemas"]["GeneratedProgramInputSummary"];
        } | null;
        GeneratedProgramInputSummary: {
            /** @example strength */
            primaryGoal?: string | null;
            /** @example 3 */
            trainingDaysPerWeek?: number | null;
            /** @example 45 */
            sessionDurationMinutes?: number | null;
        } & {
            [key: string]: unknown;
        };
        ProgramProgressionEvent: {
            /** @example pe_123 */
            id: string;
            /** @example exercise_pushups */
            exercise_id: string;
            /** @example catalog_pushups */
            catalog_exercise_id: string | null;
            /** @example pushups */
            exercise_key: string;
            /** @example Push-ups */
            exercise_name: string;
            /** @enum {string} */
            direction: "up" | "down";
            /** @example performed above target in 2 sessions */
            reason: string;
            before: components["schemas"]["ProgressionEventState"];
            after: components["schemas"]["ProgressionEventState"];
            /**
             * @description UTC timestamp in ISO 8601 format.
             * @example 2026-03-29T12:00:00.000Z
             */
            created_at: string;
        };
        ProgressionEventState: {
            /** @example 2 */
            sets: number;
            /** @example 8 */
            min: number;
            /** @example 12 */
            max: number;
        };
        ProgramRuntimeState: {
            /** @example 2026-04-12T12:00:00.000Z */
            last_session_logged_at: string | null;
            /** @example 2026-04-16T12:00:00.000Z */
            last_progression_run_at: string | null;
            /**
             * @description UTC timestamp in ISO 8601 format.
             * @example 2026-03-29T12:00:00.000Z
             */
            created_at: string;
            /**
             * @description UTC timestamp in ISO 8601 format.
             * @example 2026-03-29T12:00:00.000Z
             */
            updated_at: string;
        } | null;
        ActiveProgramVersion: {
            /** @enum {string} */
            status: "active";
            /** @example program_family_123 */
            program_family_id: string;
            /** @example 3 */
            version_number: number;
            /** @example program_122 */
            previous_version_id: string | null;
            /**
             * @description UTC timestamp in ISO 8601 format.
             * @example 2026-03-29T12:00:00.000Z
             */
            created_at: string;
            /**
             * @description UTC timestamp in ISO 8601 format.
             * @example 2026-03-29T12:00:00.000Z
             */
            updated_at: string;
            /** @example generated */
            source: string;
        };
        CurrentVersionChanges: {
            /** @example 2 schedule days were remapped (Monday, Thursday). */
            summary: string;
            /**
             * @example [
             *       "2 schedule days were remapped (Monday, Thursday).",
             *       "1 session was added (Mobility Reset)."
             *     ]
             */
            highlights: string[];
            stats: {
                /** @example 2 */
                schedule_changes: number;
                /** @example 1 */
                workouts_added: number;
                /** @example 0 */
                workouts_removed: number;
                /** @example 2 */
                exercises_added: number;
                /** @example 1 */
                exercises_removed: number;
                /** @example 3 */
                target_changes: number;
                /** @example 1 */
                set_cap_changes: number;
                /** @example false */
                renamed: boolean;
            };
        };
        ProgramDefinition: {
            /** @example default */
            id: string;
            /** @example Base Program */
            name: string;
            schedule: components["schemas"]["ProgramSchedule"];
            workouts: {
                [key: string]: components["schemas"]["ProgramWorkout"];
            };
        };
        ProgramMutationResponse: {
            /** @enum {boolean} */
            ok: true;
            /** @example Program saved */
            message: string;
            program: components["schemas"]["ProgramDefinition"] & {
                /** @example program_123 */
                version_id: string;
            };
        };
        GeneratedProgramResponse: {
            /** @enum {boolean} */
            ok: true;
            /** @example Program regenerated */
            message: string;
            program: components["schemas"]["ProgramDefinition"] & {
                /** @example program_123 */
                version_id: string;
                /** @example generated */
                source: string;
            };
            generator: components["schemas"]["GeneratedProgramMetadata"];
        };
        RecommendationDraftStructureSelectRequest: {
            /** @example rd_123 */
            draft_id: string;
            /** @example 4_day */
            structure_id: string;
        };
        RecommendationDraftExerciseReplaceRequest: {
            /** @example rd_123 */
            draft_id: string;
            /** @example A:0 */
            slot_id: string;
            /** @example catalog_pushups */
            catalog_exercise_id: string;
        };
        RecommendationDraftActivateResponse: {
            /** @enum {boolean} */
            ok: true;
            /** @example Recommendation draft activated */
            message: string;
            program: components["schemas"]["ProgramDefinition"] & {
                /** @example program_123 */
                version_id: string;
                /** @example generated */
                source: string;
            };
            generator: components["schemas"]["GeneratedProgramMetadata"];
            recommendation_draft: {
                /** @example rd_123 */
                id: string;
                /** @enum {string} */
                status: "activated";
                /** @example 3_day */
                selected_structure_id: string;
                /** @example program_123 */
                activated_program_id: string;
                /**
                 * @description UTC timestamp in ISO 8601 format.
                 * @example 2026-03-29T12:00:00.000Z
                 */
                activated_at: string;
                /**
                 * @description UTC timestamp in ISO 8601 format.
                 * @example 2026-03-29T12:00:00.000Z
                 */
                updated_at: string;
            };
        };
        RecommendationDraftActivateRequest: {
            /** @example rd_123 */
            draft_id: string;
        };
        ProgressionRunResponse: {
            /** @enum {boolean} */
            ok: true;
            /**
             * @description Date string in YYYY-MM-DD format.
             * @example 2026-03-11
             */
            progression_date: string;
            result: {
                changed: components["schemas"]["ProgressionChange"][];
                skipped: components["schemas"]["ProgressionSkipped"][];
            };
        };
        ProgressionChange: {
            /** @example pushups */
            id: string;
            /** @example Push-ups */
            name: string;
            /** @enum {string} */
            direction: "up" | "down";
            /** @example performed above target in 2 sessions */
            reason: string;
            before: components["schemas"]["ProgressionBounds"];
            after: components["schemas"]["ProgressionBounds"];
        };
        ProgressionBounds: {
            /** @example 2 */
            sets: number;
            /** @example 8 */
            min: number;
            /** @example 12 */
            max: number;
        };
        ProgressionSkipped: {
            /** @example pushups */
            id: string;
            /** @example performance stayed within target range */
            reason: string;
        };
        LogCreateResponse: {
            /** @enum {boolean} */
            ok: true;
            /**
             * @description Date string in YYYY-MM-DD format.
             * @example 2026-03-11
             */
            date: string;
            entry: components["schemas"]["LegacyLogEntry"];
            session: components["schemas"]["WorkoutSessionRecord"];
        };
        LegacyLogEntry: {
            /**
             * @description Date string in YYYY-MM-DD format.
             * @example 2026-03-11
             */
            date: string;
            /** @example A */
            workout_type: string | null;
            exercises: components["schemas"]["SessionLogExercise"][];
            /** @example Felt strong today */
            note: string;
            /** @example [] */
            unmatched: string[];
            /** @enum {string} */
            source: "json" | "text" | "legacy-kv";
            /** @example session_123 */
            session_id: string;
            /**
             * @description UTC timestamp in ISO 8601 format.
             * @example 2026-03-29T12:00:00.000Z
             */
            created_at: string;
        };
        SessionLogExercise: {
            /** @example pushups */
            id: string;
            /** @example Push-ups */
            name: string;
            /**
             * @example [
             *       10,
             *       10,
             *       9
             *     ]
             */
            sets: number[];
        };
        WorkoutSessionRecord: {
            /** @example session_123 */
            id: string;
            /**
             * @description Date string in YYYY-MM-DD format.
             * @example 2026-03-11
             */
            sessionDate: string;
            /** @example A */
            workoutType: string | null;
            /** @example Workout A */
            workoutName: string | null;
            /** @example Felt strong today */
            note: string;
            /** @enum {string} */
            source: "json" | "text" | "legacy-kv";
            /** @example null */
            rawText: string | null;
            /** @example [] */
            unmatched: string[];
            /**
             * @description UTC timestamp in ISO 8601 format.
             * @example 2026-03-29T12:00:00.000Z
             */
            createdAt: string;
            /**
             * @description UTC timestamp in ISO 8601 format.
             * @example 2026-03-29T12:00:00.000Z
             */
            updatedAt: string;
            exercises: components["schemas"]["WorkoutSessionExercise"][];
        };
        WorkoutSessionExercise: {
            /** @example se_123 */
            id: string;
            /** @example exercise_123 */
            programExerciseId: string | null;
            /** @example catalog_pushups */
            catalogExerciseId: string | null;
            /** @example pushups */
            exerciseKey: string | null;
            /** @example Push-ups */
            exerciseName: string;
            /**
             * @example reps
             * @enum {string|null}
             */
            exerciseType: "reps" | "time" | "cycles" | null;
            /** @example true */
            matched: boolean;
            /** @example 0 */
            sortOrder: number;
            /**
             * @example [
             *       10,
             *       10,
             *       9
             *     ]
             */
            sets: number[];
        };
        JsonLogRequest: {
            /**
             * @description Date string in YYYY-MM-DD format.
             * @example 2026-03-11
             */
            session_date?: string;
            /** @example Felt strong today */
            note?: string;
            /** @example A */
            workout_type?: string | null;
            exercises?: components["schemas"]["JsonLogExercise"][];
        };
        JsonLogExercise: {
            /** @example pushups */
            id: string;
            /** @example Push-ups */
            name?: string;
            /**
             * @example [
             *       10,
             *       10,
             *       9
             *     ]
             */
            sets: number[];
        };
        SessionsListResponse: {
            sessions: components["schemas"]["WorkoutSessionRecord"][];
            /** @example 10 */
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
